import { useRouter } from "next/router";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
// Only loads the YouTube player
import ReactPlayer from "react-player/youtube";
import { useEffect, useState } from "react";
import Link from "next/link";


function watch() {
  
  const [hasWindow, setHasWindow] = useState(false);
  useEffect(() => {
    if (typeof window !== "undefined") {
      setHasWindow(true);
    }
  }, []);

  const router = useRouter()
  const { id, title } = router.query
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Watch <Link href="/">HealthTube!</Link>
        </h1>
        <p className={styles.description}>{title}</p>
        {hasWindow && (
          <ReactPlayer
            url={`https://www.youtube.com/watch?v=${id}`}
            controls
            width={"80vw"}
            height={"80vh"}
          />
        )}
      </main>
    </div>
  );
}

export default watch;
